Make Redundancy.redundancySet public
stmcginnis/gofish pull request #356
Opened 2024-07-11 17:31 UTC by pereztr5

This change makes it so we can access the `RedundancySet` param, which contains all actual Power Supplies vs what is listed in `.PowerSupplies` as that can contain anything in the PSU slots, which sometimes are fans and not actual power supplies.

2024-07-11 18:30 UTC, stmcginnis requested changes
Please expose this by adding an accessor method so it is consistent with the other object/related-object acccess.

For example:
https://github.com/stmcginnis/gofish/blob/main/redfish/power.go#L425

Thanks for working on this!

2024-07-29 21:11 UTC, stmcginnis reviewed
Thanks - just a couple minor things.

2024-07-29 21:11 UTC, stmcginnis commented on redfish/power.go
> +func (power *Power) GetRedundancySet(memberID int) []PowerSupply {
Please rename the method to just be `RedundancySet(memberID int)`.

2024-07-29 21:11 UTC, stmcginnis commented on redfish/power.go
> +	for _, psLink := range power.Redundancy[memberID].redundancySet {
Would probably be good to make sure `memberID` is actually present before accessible `.redundancySet`.

2024-07-29 21:11 UTC, pereztr5 commented
Hey @stmcginnis, I'm unsure if I made this function consistent with your other object/related-object access as I could not use the `redfish.Redundancy[].redundancySet` links. These links look like:
```
# /redfish/v1/Chassis/1/Power | jq '.Redundancy[].RedundancySet'
[
  {
    "@odata.id": "/redfish/v1/Chassis/1/Power#/PowerSupplies/0"
  },
  {
    "@odata.id": "/redfish/v1/Chassis/1/Power#/PowerSupplies/1"
  },
  {
    "@odata.id": "/redfish/v1/Chassis/1/Power#/PowerSupplies/2"
  },
  {
    "@odata.id": "/redfish/v1/Chassis/1/Power#/PowerSupplies/3"
  },
  {
    "@odata.id": "/redfish/v1/Chassis/1/Power#/PowerSupplies/4"
  },
  {
    "@odata.id": "/redfish/v1/Chassis/1/Power#/PowerSupplies/7"
  }
]
```

Hitting those links gives back the same response as `/redfish/v1/Chassis/1/Power` vs. the individual `redfish.PowerSupply`, and so in both cases, you need to use the `.PowerSupplies[]` field from the response to get the actual `redfish.PowerSupply`.

My goal is to get the `[]redfish.PowerSupply` for the given redundancy group so that it does not include anything that is not part of it. That is why I made the function just filter the `[]redfish.PowerSupply`.

2024-07-29 21:16 UTC, stmcginnis commented
> My goal is to get the []redfish.PowerSupply for the given redundancy group so that it does not include anything that is not part of it. That is why I made the function just filter the []redfish.PowerSupply.

Yep, that makes sense. Those are jsonpath links, so in this case they are self-referential. I think the approach makes sense.

2024-07-29 21:35 UTC, pereztr5 commented
Thanks for the quick feedback. I have made the adjustments and added more to the comment.

2024-07-29 21:39 UTC, stmcginnis approved these changes
Thanks for the updates - looks good!

2024-07-29 22:09 UTC, merged